# -*- coding: utf-8 -*-
"""PLV_MODULE1_PIPELEINE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHs5S8M8Siu6Vdqa2T74fzWEpjaL8ZN7
"""



"""YOUTUBE STREAM IMAGE FETCHER"""

import cv2
import pafy
#from google.colab.patches import cv2_imshow
import time
import os
import subprocess
import string
import random
from datetime import datetime
import boto3
from pprint import pprint
import pathlib

## capturing the image from the remote URL YOUTUBE STREAM
url = "https://www.youtube.com/watch?v=e9LYewJGQlk"

start = time.time()
video = pafy.new(url)
best = video.getbest(preftype="mp4")

capture = cv2.VideoCapture()
capture.open(best.url)

success,image = capture.read()

current_date = datetime.now()
str_date = current_date.strftime('%Y-%m-%dT%H:%M:%S.%f%z')

 
# initializing size of string
N = 7
 

# generating random strings
res = ''.join(random.choices(string.ascii_lowercase +
                             string.digits, k=N))
 
filename = str_date + '_' + res + '.jpg'

# Directory
directory = "images/"
  
# Parent Directory path
parent_dir = "/home/ubuntu/ms_final_project/"
  
# Path
dir_path = os.path.join(parent_dir, directory)
  
# Saving the file

cv2.imwrite(os.path.join(dir_path , filename), image)
cv2.destroyAllWindows()
capture.release()

# ! python detect.py --weights weights/S-512.pt --source /content/gdrive/MyDrive/YOLOv5/urban-detection/yolov5/2022-10-16T09:31:22.012493_84anjnf.jpg --img-size 512









